####
######################## Запити продукти ########################################################################################

### Створити новий продукт
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/products
Content-Type: application/json

{
  "name": "Test",
  "description": "Test",
  "unit": "ампула",
  "minQuantityThreshold": 10
}

### Отримати список продуктів
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/products
Content-Type: application/json

#####################################################################
######################## Запити постачальники ########################################################################################
/
### Створити нового постачальника
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/suppliers
Content-Type: application/json

{
  "name": "Test1",
  "email": "sales@test1.ua",
  "phone": "+380111111211",
  "contactPerson": "Менеджер Test1"
}

### Отримати усіх постачальників
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/suppliers
Content-Type: application/json

#####################################################################
######################## Запити для інвертаризації ########################################################################################
/

### Зробити ресток
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/inventory/restock?userId=11111111-1111-1111-1111-111111111111
Content-Type: application/json

{
  "productId": "3a67eaf7-d4d2-49b6-8b3e-4133eccbbdaf",
  "supplierId": "a6f2bf5f-e9be-4e3b-9ed7-a89e6ea14191",
  "quantity": 1000,
  "purchasePrice": 25.50,
  "expiryDate": "2026-12-31",
  "batchNumber": "SERIES-2025-12",
  "sku": "48200111222"
}

### Зробити списання
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/inventory/usage?userId=11111111-1111-1111-1111-111111111111
Content-Type: application/json

{
  "productId": "3a67eaf7-d4d2-49b6-8b3e-4133eccbbdaf",
  "quantity": 20,
  "reason": "Usage test"
}

### Отримати повну історію
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/inventory/history
Content-Type: application/json

### Отримати історію продукту
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111111/inventory/history/3a67eaf7-d4d2-49b6-8b3e-4133eccbbdaf
Content-Type: application/json
