####
######################## Запити продукти ########################################################################################

### Створити новий продукт
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/products
Content-Type: application/json

{
  "name": "Лідокаїн",
  "description": "Знеболююче",
  "unit": "ампула",
  "minQuantityThreshold": 10
}

### Отримати список продуктів
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/products
Content-Type: application/json

#####################################################################
######################## Запити постачальники ########################################################################################
/
### Створити нового постачальника
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/suppliers
Content-Type: application/json

{
  "name": "Фармак",
  "email": "sales@farmak.ua",
  "phone": "+380111111211",
  "contactPerson": "Менеджер Фармак"
}

### Отримати усіх постачальників
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/suppliers
Content-Type: application/json

#####################################################################
######################## Запити для інвертаризації ########################################################################################
/

### Зробити ресток
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/inventory/restock?userId=11111111-1111-1111-1111-111111111112
Content-Type: application/json

{
  "productId": "4c1bb52d-0aa0-4f28-82b9-25aeb5233a0b",
  "supplierId": "fefee312-625e-4da6-9532-2c871c87d720",
  "quantity": 20,
  "purchasePrice": 30.50,
  "expiryDate": "2026-12-31",
  "batchNumber": "SERIES-2025-12",
  "sku": "48200111222"
}

### Зробити списання
POST http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/inventory/usage?userId=11111111-1111-1111-1111-111111111112
Content-Type: application/json

{
  "productId": "4c1bb52d-0aa0-4f28-82b9-25aeb5233a0b",
  "quantity": 1,
  "reason": "Usage test"
}

### Отримати повну історію
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/inventory/history
Content-Type: application/json

### Отримати історію продукту
GET http://localhost:8080/api/clinics/11111111-1111-1111-1111-111111111112/inventory/history/4c1bb52d-0aa0-4f28-82b9-25aeb5233a0b
Content-Type: application/json
